### ISSUE TITLE
Ukol 8, 9, 10, 11

### ISSUE THREAD

**Issue by klarunkax** [klarunkax/kurzpython2#2]
https://github.com/klarunkax/kurzpython2/blob/master/Lekce8/DU8.py
https://github.com/klarunkax/kurzpython2/blob/master/Lekce9/DU9.py
https://github.com/klarunkax/kurzpython2/blob/master/Lekce10/DU10.1.py
https://github.com/klarunkax/kurzpython2/blob/master/Lekce10/DU10.2..py
https://github.com/klarunkax/kurzpython2/blob/master/Lekce11/DU11.py

**Comment by pesikj** [comment]
Ahoj Kláro, u úkolu 8.2 chybí predikce a trend by měl být multiplikativní, ty ho máš aditivní. Lze to upravit třeba takto:

```
#Vytvoř predikci hodnot časové řady pomocí Holt-Wintersovy metody na 12 měsíců. Sezónnost nastav jako 12 a uvažuj multiplikativní model pro trend i sezónnost. Výsledek zobraz jako graf.
from statsmodels.tsa.holtwinters import ExponentialSmoothing
mod = ExponentialSmoothing(MLTOLLS["python"], seasonal_periods=12, trend="mul", seasonal="mul", use_boxcox=True, initialization_method="estimated",)
res = mod.fit()

df_forecast = pandas.DataFrame(res.forecast(12), columns=["Prediction"])
MLTOLLS = pandas.concat([MLTOLLS, df_forecast])
print(MLTOLLS.columns)
MLTOLLS["HM"] = res.fittedvalues
MLTOLLS[["HM", "python", "Prediction"]].plot()
plt.show()
```

**Comment by pesikj** [comment]
U 9.1 ti chybí odvození vzorce pro precision_score, mělo by to být 80/(80+47). :-)

**Comment by pesikj** [comment]
U úkolu 11.1 máš jednu dvojici špatně a jednu správně. Poznáš, která je špatně? Důležitá je počet pozorování a tím pádem výška silhouette grafu. :-)

**Comment by pesikj** [comment]
Úkoly za 10. lekci jsou v pohodě :-)

**Comment by pesikj** [comment]
@klarunkax Body jsem ti za všechny úkoly samozřejmě zapsal a o certifikát nepřijdeš, ale jestli budeš mít čas, tak se na to prosím ještě podívej :-)
